# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SimpleApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SimpleApp
  pod 'RealmSwift', '10.44.0'
  target 'SimpleAppTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'iOSSnapshotTestCase'
  end
end


